copyright: Copyright &copy; 2023 hotio<br>Logos based on work by <a href="https://www.flaticon.com/authors/freepik">Freepik</a> from <a href="https://www.flaticon.com">flaticon.com</a> and <a href="https://freeicons.io/profile/6200">Soni Sokell</a> on <a href="https://freeicons.io">freeicons.io</a>
edit_uri: 'website/edit/master/docs'

extra:
  social:
  - icon: fontawesome/solid/heart
    link: 'https://hotio.dev/donate'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://hotio.dev/discord'
    name: Discord
  - icon: fontawesome/brands/docker
    link: 'https://engels74.net/dockerhub'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://engels74.net/github'
    name: GitHub

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - redirects:
      redirect_maps:
        discord.md: 'https://discord.gg/FycMN9gTC3'
        dockerhub.md: 'https://hub.docker.com/u/engels74'
        github.md: 'https://github.com/engels74'
        donate.md: 'https://hotio.dev/#donations'
        faq.md: 'https://hotio.dev/faq'
        pia.md: https://www.privateinternetaccess.com/offer/hotio.dev_hsm018qg
        proton.md: https://go.getproton.me/aff_c?offer_id=26&aff_id=7223
        cyberghost.md: https://www.cyberghostvpn.com/offer/hatio.dev_2x3ni6r
        torguard.md: https://torguard.net/aff.php?aff=7533

repo_name: engels74
repo_url: https://github.com/engels74
site_author: engels74
site_description: Documentation for all Docker images maintained by engels74.
site_name: engels74.net
site_url: https://engels74.net

theme:
  icon:
    repo: fontawesome/brands/github
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  language: en
  logo: img/engels74.svg
  name: material
  palette:
    scheme: hotio
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
  - admonition

nav:
- Home: index.md
- Containers:
  - Apps:
    - engels74/qflood: containers/autoscan.md
    - hotio/requestrr: https://hotio.dev/containers/requestrr

- Guides:
  - TorGuard: https://hotio.dev/guides/torguard.md
- Scripts:
  - Pullio: https://hotio.dev/scripts/pullio.md
  - Arr Discord Notifier: https://hotio.dev/scripts/arr-discord-notifier.md
- FAQ: faq.md
